output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks-cluster.aws_eks_cluster.this.endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks-cluster.aws_security_group.cluster
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks-cluster.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks-cluster.config_map_aws_auth
}

output "node_groups" {
  description = "Outputs from node groups"
  value       = module.eks-cluster.node_groups
}

output "worker_iam_role_name" {
  description = "Outputs from worker_iam_role_name"
  value       = module.eks-cluster.aws_iam_role.workers
}

output "private_subnet_output" {
  description = "Outputs from VPC Module with private_subnets"
  value = module.vpc.aws_subnet.private

output "public_subnets_output" {
  description = "Outputs from VPC Module with public_subnets"
  value = module.vpc.aws_subnet.public
}

output "vpc_id_output" {
  description = "Outputs from VPC Module with VPC ID"
  value = module.vpc.vpc_id
}

output "cluster_id" {
  description = "Outputs from cluster_id"
  value       = module.eks-cluster.cluster_id
}
