output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks-cluster.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks-cluster.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks-cluster.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks-cluster.config_map_aws_auth
}

# output "region" {
#   description = "AWS region."
#   value       = var.region
# }

output "node_groups" {
  description = "Outputs from node groups"
  value       = module.eks-cluster.node_groups
}

output "cluster_oidc_issuer_url" {
  description = "Outputs from cluster_oidc_issuer_url"
  value       = module.eks-cluster.cluster_oidc_issuer_url
}
/*
output "worker_autoscaling_policy_arn" {
  description = "Outputs from worker_autoscaling_policy_arn"
  value       = module.eks-cluster.worker_autoscaling_policy_arn
}
*/

output "worker_iam_role_name" {
  description = "Outputs from worker_iam_role_name"
  value       = module.eks-cluster.worker_iam_role_name
}

output "worker_iam_role_arn" {
  description = "Outputs from worker_iam_role_arn"
  value       = module.eks-cluster.worker_iam_role_arn
}


/*
output "aws_s3_bucket_name" {
  description = "Outputs from aws_s3_bucket resource"
  value       = aws_s3_bucket.backend_bucket.id
}
*/
output "private_subnet_output" {
  description = "Outputs from VPC Module with private_subnets"
  value = module.vpc.private_subnets
}

output "public_subnets_output" {
  description = "Outputs from VPC Module with public_subnets"
  value = module.vpc.public_subnets
}

output "vpc_id_output" {
  description = "Outputs from VPC Module with VPC ID"
  value = module.vpc.vpc_id
}

output "cluster_id" {
  description = "Outputs from cluster_id"
  value       = module.eks-cluster.cluster_id
}
/*
output "aws_route53_zone_id" {
  description = "Outputs from aws_route53_zone_id"
  value       = data.aws_route53_zone.selected.zone_id
}
*/